### ISSUE TITLE
SketchUp file?

### ISSUE THREAD

**Issue by leo60228** [ncarandini/KiCad-RP-Pico#1]
VRML files are pretty picky (as you've probably noticed due to the scaling issue). I haven't been able to get your file to load in any program other than KiCad. Could you share the SketchUp file you made?
For KiCad specifically, as far as I know https://github.com/easyw/kicadStepUpMod is the best way to create a working VRML.

**Comment by ncarandini** [comment]
Sure, I've added the SketchUp file.
