### ISSUE TITLE
Wrong classification of pins

### ISSUE THREAD

**Issue by bablokb** [ncarandini/KiCad-RP-Pico#2]
Your GND and power pins should be classified as power-input.

**Comment by ncarandini** [comment]
This isssue is not related with my work that is about the 3D representation of the device. Anyway I'll check if I can fix it on the other libraries. Any help on to do this is much appreciated.

**Comment by bablokb** [comment]
I have created a pcb based on your work, see https://github.com/bablokb/pi-pico-devboard-hat. You should find updated versions of the component in the `*rescue.*`-files within the `pi-pico-devboard-hat.kicad`-directory.

**Comment by ncarandini** [comment]
Ok done.
![image](https://user-images.githubusercontent.com/139274/128375789-15812e6b-c210-4eeb-b02d-7da4f3d1f437.png)

**Comment by raybellis** [comment]
This seems like it might be incomplete?   The GND at pin38 is still flagged as Bidrectional
