### ISSUE TITLE
component shows up as Raspberry Pi

### ISSUE THREAD

**Issue by bablokb** [ncarandini/KiCad-RP-Pico#3]
When adding as a component, it shows up as 'Raspberry Pi' and  not as 'Pico'

**Comment by ncarandini** [comment]
I've only worked on the 3D model representation, other info are contained in the other libraries I've collected from the cited other GitHub project. I'll see if I can fix it anyway, but not in the short run. Any help is much aprreciated.

**Comment by ncarandini** [comment]
Ok, done:
![image](https://user-images.githubusercontent.com/139274/128375444-15a614d3-b878-40ec-acd2-454e421e2398.png)
