### ISSUE TITLE
Change label of pins

### ISSUE THREAD

**Issue by bablokb** [ncarandini/KiCad-RP-Pico#4]
Not really an issue, more a feature-request/suggestion: change the labels of the pins, e.g. GPIO0/TX

**Comment by ncarandini** [comment]
Labels are not part of the 3D Model, I'll investigate on how to change them in the other libraries. thanks anyway for the suggestion. Moreover labels are in the bottom face of the real device, so I'll investigate more also on this.

**Comment by ncarandini** [comment]
I've checked the Pin illustration for Raspberry Pi Pico and I dont think is a good idea to change label of pins as you suggested.
As an example, for GP0 we have UART0-TX and SPI0-RX. So I've decided to not change the label of pins.

![image](https://user-images.githubusercontent.com/139274/128211612-06d29b69-4e6f-4555-b47f-955ed386ae3e.png)
