### ISSUE TITLE
Scale and position issue

### ISSUE THREAD

**Issue by pkoning2** [ncarandini/KiCad-RP-Pico#5]
When I copied over the Pico.wrl file and told KiCAD to use it, I could see it but the size and position was wrong.  I got it to come out right by changing the 3d model settings:

Scale x/y/z: 10
X offset: -0.412 in
Y offset: -1.003 in

No big deal but I was puzzled that this was needed, especially the scaling.

**Comment by ncarandini** [comment]
It's my fault, I've created the .wrl file from Sketchup and simething went wrong. Please follow the [Install instructions](https://github.com/ncarandini/KiCad-RP-Pico/blob/main/Install%20instructions.md) to workaround it until I've time to fix it.
